### ISSUE TITLE
Support for big files?

### ISSUE THREAD

**Issue by sevenzerotwo** [raniaamina/citramanik-qt#4]
Hi! In before, thank you for your hardwork on this Inkscape exporter project, it's so useful! But anyway, do you plan on making Citramanik support for exporting big files? I have this error when i exporting my .pdf document and maybe it's because of big file (i guessed it from "huge input lookup" error, and my .svg file are about 200mb)
![image](https://user-images.githubusercontent.com/80304158/145424706-37c4a39f-9f0a-47fa-b8a4-89478e058663.png)

**Comment by raniaamina** [comment]
Hi, this sometimes happen. The simple solution is if your SVG contain bitmap files, make it to link mode instead of embed.

**Comment by raniaamina** [comment]
btw, please open the issue here:
[Citramanik Repo](https://github.com/devlovers-id/citramanik-qt)

**Comment by sevenzerotwo** [comment]
Alright, thank you for your solution! I gotta open this issue on devlovers's repo. I close this issue right now.
